### ISSUE TITLE
Please specify a task size Error

### ISSUE THREAD

**Issue by AlexanderBond** [ucbdrive/scalabel#20]
Hello dear Team,

After filling out the form on the start page, it was not possible for me to start the project due to this issue. After clicking the Enter button I always get this message: “Please specify a task size.”

Two buttons mentioned in the manual are also missing: “Go to dashboard” and “Go to Vendor dashboard”.

I use scalabel in my University project, so it would be great if you cold help me with thees issues!

Sincerely,
Alexander

**Comment by AVCarreiro** [comment]
I suppose you're facing this problem when choosing "video". What I do is I first select "image", then choose the task size, and after this I'm able to switch back to "video" and it works.

**Comment by seanremy** [comment]
Hi, apologies for this issue. It should be fixed in the current version. Can you see if it has resolved the issue on your end?

**Comment by AVCarreiro** [comment]
Hi, I pulled the current version, cleaned the cache, but the task size form when "video" is selected is still not visible.

**Comment by xanderchf** [comment]
Hello, in the latest version task size is no longer a required field for video; only frame rate is needed. Let me know if you have other questions.

**Comment by AVCarreiro** [comment]
It stills asks to specify the task size, just confirmed it now again. Using Chrome
