### ISSUE TITLE
Quickdraw fails to select target polygon

### ISSUE THREAD

**Issue by deruci** [ucbdrive/scalabel#5]
Hi, we are currently working on instance segmentation with this tool but when we are facing a problem when using Quickdraw option. The symptom is as follows : 

When we draw a new shape that shares borders with multiple instances, polygon cannot be selected all of the sudden even when the button is toggled. Then, if we put down the next point, it is placed on a random vertex on another instance. 

We didn't face this issue when sharing borders with one instance, but when it gets to multiple instances, we get this issue.

Thanks!

**Comment by bhpfelix** [comment]
Hi, thanks for using our tool! This bug should be resolved now. Please check it out :)

**Comment by deruci** [comment]
Thank you for fast response.  We are still having issues with the updated version.
It works fine for a while, but we encounter issues when we draw new shape and use quickdraw.

![scalabel](https://user-images.githubusercontent.com/5226447/41911264-22b94c42-7987-11e8-8782-61791378c2da.png)

Scenario:
 - Consecutively stiching polygons together in quickdraw mode (see attached)

Issue:
 - When selecting a new target polygon, one specific vertex gets returns by the selectedBy event regardless of the mouse position.

We think the above issue is the root of the bug.

**Comment by deruci** [comment]
maybe the number of vertices of polygon would be the problem..
After drawing a polygon with so many vertices, polygon drawing would fail when I double-click same vertex  while drawing a new polygon. Situation is like below:
![scalabel2](https://user-images.githubusercontent.com/5226447/41914608-9bf622c2-798e-11e8-8fe4-3edf3e4a145e.png)
![scalabel3](https://user-images.githubusercontent.com/5226447/41914613-9f9e4eea-798e-11e8-83a6-ad7594436507.png)

Whenever I try to draw a new polygon, If fails when I put two vertices in the same position.
Buggy vertex keeps same

**Comment by bhpfelix** [comment]
Ah, I see. Thanks for pointing it out. I think one of the root causes of this behavior may be there is interpolation happening on the hidden canvas. We use a hidden canvas to do hit region detection, where each interactable shape was assigned a unique color code. When we draw vertex, canvas seems to automatically interpolate the color of some pixels along the peripheral of the circle, which leads to wrongly selected shape. We will try to work out a way to disable interpolation.

The vertex gets returned instead of polygon case seems a little different, but I was having some trouble recreating the behavior with the updated version. Could you please double check if the line below is present in the code base?
https://github.com/ucbdrive/scalabel/blob/fd552c14d688ff4d9633077aaf9f41b972e32c29/app/src/js/seg2d.js#L190

**Comment by bhpfelix** [comment]
Hi, I found the bug that's creating the issue and made a fix attempt in the [hidden_color_bug_fix](https://github.com/ucbdrive/scalabel/tree/hidden_color_bug_fix) branch. Please let me know if the problem persists.
